import { WorkItemProps } from '~/components/common/work-item';

export const workItemsList: Omit<WorkItemProps, 'last' | 'number'>[] = [
  {
    position: 'Fullstack Developer (Python + Angular)',
    companyName: 'Apptimia',
    companyUrl: 'https://apptimia.com',
    endDate: 'Present',
    startDate: '2024',
    skills: [
      'Python',
      'Django',
      'Celery',
      'S3',
      'SQS',
      'SocetIO',
      'Angular 2+',
      'TypeScript',
      'Angular Material',
      'SASS',
    ],
    list: [
      'Maintained the Angular codebase, improving UX and performance, particularly on map-heavy views.',
      'Built an automation pipeline using Amazon S3, Python, and SQS to efficiently process large volumes of geospatial images and handle increasing workloads.',
      'Deployed MapProxy to translate tiles from existing services, reducing costs and saving time, with a custom plugin for seamless integration with specific customer data sources.',
    ],
  },
  {
    position: 'Frontend Developer (React + Electron)',
    companyName: 'Apptimia',
    companyUrl: 'https://apptimia.com',
    endDate: '2024',
    startDate: '2023',
    skills: [
      'React',
      'Electron',
      'TypeScript',
      'Styled-Components',
      'Webpack',
      'SQLite',
      'RTL',
      'Redux Toolkit',
    ],
    list: [
      'Built an Electron app with React and TypeScript for seamless interaction with local applications, supported by clear architecture diagrams.',
      'Created a flexible design system from Adobe XD wireframes, maintaining consistency while adapting to new features.',
      'Integrated a Greenfield app with legacy systems up to 15 years old, ensuring consistent communication and reliability.',
      'Managed complex application-wide state, ensuring seamless business logic and component interaction.',
      'Contributed tech insights, recommending performance and UX improvements.',
      'Developed unit tests for critical components, ensuring high code quality.',
    ],
  },
  {
    position: 'Frontend Developer (Angular)',
    companyName: 'Apptimia',
    companyUrl: 'https://apptimia.com',
    endDate: '2022',
    startDate: '2023',
    skills: [
      'Angular 2+',
      'RxJS',
      'TypeScript',
      'Angular Material',
      'SASS',
      'Cypress',
      'NgRx',
    ],
    list: [
      'Overhauled data flows with pagination, fragmented data loading, and debounced API requests to improve performance and streamline the buying process.',
      'Revamped end-to-end test suites to reduce CI time and improve test reliability, ensuring high-performance code in production.',
      'Updated outdated packages to improve system stability and ensure compatibility with the latest standards and supported technologies.',
      'Improved UIs for essential features to enhance UX and overall design',
      'INtroduced additional E2E tests using cypress to ensure correct user flows across the application',
    ],
  },
];
