import { WorkItemProps } from '~/components/common/work-item';

export const workItemsList: Omit<WorkItemProps, 'last' | 'number'>[] = [
  {
    position: 'Software Engineer (Rotics)',
    companyName: 'Apptimia',
    companyUrl: 'https://apptimia.com',
    startDate: '2025',
    endDate: 'Present',
    skills: [
      'Python',
      'ROS2',
      'YOLO',
      'AI',
      'Nvidia Jetson',
      'Docker',
      'DepthAI',
      'Go2 Unitree',
    ],
    list: [
      'Created multipurpose system based on Unitree Go2 robot with capabilities for remote operation, threat detection and room mapping.',
      'Deployed AI models on edge devices like Nvidia Orin Nano, for real-time object detection.',
      'Built packages for ROS2 ecosystem to interface with hardware components and AI models.',
      'Integrated AI models with robotic control system to enable automatic threat detection and user notification.',
      'Levaraged Docker for consistent developement and deployment as well as for easy environment separation of packages.',
    ],
  },
  {
    position: 'Fullstack Developer (Python + Angular)',
    companyName: 'Apptimia',
    companyUrl: 'https://apptimia.com',
    endDate: '2025',
    startDate: '2024',
    skills: [
      'Python',
      'Django',
      'FastAPI',
      'AWS',
      'S3',
      'SQS',
      'Postgres',
      'PostGIS',
      'Terraform',
      'Docker',
      'Angular 2+',
      'TypeScript',
      'Angular Material',
      'SASS',
    ],
    list: [
      'Improved system performance and reliability by rewriting outdated map services in Python and FastAPI.',
      'Improved infrastructure as code creating missing resources, deploying new ones and fixing deprecated configurations in Terraform.',
      'Built an automation pipeline using Amazon S3, Python, and SQS to efficiently process large volumes of geospatial images and handle increasing workloads.',
      'Deployed proxy service to translate tiles from existing services, reducing costs and saving time.',
      'Maintained the Angular codebase, improving UX and performance, particularly on map-heavy views.',
    ],
  },
  {
    position: 'Frontend Developer (React + Electron)',
    companyName: 'Apptimia',
    companyUrl: 'https://apptimia.com',
    endDate: '2024',
    startDate: '2023',
    skills: [
      'React',
      'Electron',
      'TypeScript',
      'Styled-Components',
      'Webpack',
      'SQLite',
      'RTL',
      'Redux Toolkit',
    ],
    list: [
      'Built an Electron app with React and TypeScript for seamless interaction with local applications, supported by clear architecture diagrams.',
      'Created a flexible design system from Adobe XD wireframes, maintaining consistency while adapting to new features.',
      'Integrated a Greenfield app with legacy systems up to 15 years old, ensuring consistent communication and reliability.',
      'Managed complex application-wide state, ensuring seamless business logic and component interaction.',
      'Contributed technical insights, recommending performance and UX improvements.',
      'Developed unit tests for critical components, ensuring high code quality.',
    ],
  },
  {
    position: 'Frontend Developer (Angular)',
    companyName: 'Apptimia',
    companyUrl: 'https://apptimia.com',
    endDate: '2023',
    startDate: '2022',
    skills: [
      'Angular 2+',
      'RxJS',
      'TypeScript',
      'Angular Material',
      'SASS',
      'Cypress',
      'NgRx',
    ],
    list: [
      'Overhauled data flows with pagination, fragmented data loading, and debounced API requests to improve performance and streamline the buying process.',
      'Revamped end-to-end test suites to reduce CI time and improve test reliability, ensuring high-performance code in production.',
      'Updated outdated packages to improve system stability and ensure compatibility with the latest standards and supported technologies.',
      'Improved UIs for essential features to enhance UX and overall design.',
      'Introduced additional E2E tests using cypress to ensure correct user flows across the application.',
    ],
  },
];
